services:
  server:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    env_file: .env.local
    networks:
      - database
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - database
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
networks:
  database:
