import { CardRestaurant } from "@ywc19/components/CardRestaurant";
import { Caruosel } from "@ywc19/components/Caruosel";
import { SwiperSlide } from "swiper/react";
import Head from "next/head";
import { CardMenu } from "@ywc19/components/CardMenu";
import { LazyImage } from "@ywc19/components/LazyImage";

export default function Home() {
  const mock = [1, 2, 3, 4, 5, 6, 7, 8];
  const category = [
    {
      id: 0,
      img: "/assets/appetizers.png",
      name: "Appetizers",
    },
    {
      id: 1,
      img: "/assets/dishes.png",
      name: "Dishes",
    },
    {
      id: 2,
      img: "/assets/desserts.png",
      name: "Desserts",
    },
    {
      id: 3,
      img: "/assets/drinks.png",
      name: "Drinks",
    },
  ];
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center ">
        <div className="h-[656px] w-full bg-[url('/assets/bg.png')] px-[140px] pt-[368px]">
          <p className="text-h1 font-bold text-primary-main"> Content</p>
        </div>
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <div className="flex gap-x-6 pb-[56px] ">
            {category.map((item) => (
              <button
                key={item.id}
                className="flex items-center gap-x-8 rounded-xl bg-white p-8 py-6 shadow-[0px_12px_24px_-4px_rgba(145,158,171,0.12),0px_0px_2px_0px_rgba(145,_158,_171,_0.20)]"
              >
                <LazyImage src={item.img} className="h-12 w-12" />
                <p className="w-[158px] truncate text-start text-h4 font-semibold">
                  {item.name}
                </p>
              </button>
            ))}
          </div>
          <div className="w-full">
            <div className="mb-8 flex items-center gap-x-[46px]">
              <p className="flex-1 text-h3 font-semibold">
                Recommended Restaurants
              </p>
              <button className="rounded-full bg-primary-main px-[66px] py-3 text-xl font-semibold text-general-main hover:bg-primary-dark">
                See all
              </button>
            </div>
            <Caruosel sliderPerPage={2}>
              {mock.map((item) => (
                <SwiperSlide key={item}>
                  <CardRestaurant />
                </SwiperSlide>
              ))}
            </Caruosel>
          </div>
          <div className="w-full">
            <div className="mb-8 flex items-center gap-x-[46px]">
              <p className="flex-1 text-h3 font-semibold">
                Restaurant Nearby me
              </p>
              <button className="rounded-full bg-primary-main  px-[66px] py-3 text-xl font-semibold text-general-main hover:bg-primary-dark">
                See all
              </button>
            </div>
            <Caruosel sliderPerPage={2}>
              {mock.map((item) => (
                <SwiperSlide key={item}>
                  <CardRestaurant />
                </SwiperSlide>
              ))}
            </Caruosel>
          </div>
          <div className="w-full">
            <div className="mb-8 flex items-center gap-x-[46px]">
              <p className="flex-1 text-h3 font-semibold">Recommended Menu</p>
              <button className="rounded-full bg-primary-main  px-[66px] py-3 text-xl font-semibold text-general-main hover:bg-primary-dark">
                See all
              </button>
            </div>
            <Caruosel sliderPerPage={4}>
              {mock.map((item) => (
                <SwiperSlide key={item}>
                  <CardMenu />
                </SwiperSlide>
              ))}
            </Caruosel>
          </div>

          <div className="flex flex-col items-center gap-2">
            <p className="text-2xl text-white"></p>
          </div>
        </div>
      </main>
    </>
  );
}
